export const RECEIVE_ME = 'RECEIVE_ME';

export const PEOPLE_LIST = "PEOPLE_LIST";

export const UNIQUE_EMAILS_CHARACTERS = "UNIQUE_EMAILS_CHARACTERS";

export const POSSIBLE_EMAILS_DUPLICATES = "POSSIBLE_EMAILS_DUPLICATES";
